---
title: "p8105_hw6_iah2124"
author: "Iris Hart"
date: "2024-12-02"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(broom)
library(ggplot2)
library(rnoaa)
library(tidyr)
```

## Problem 1


## Problem 2
Load data and filter out city states and races unneeded 
```{r}
homicide_df <- read_csv("homicide-data.csv") |>

  mutate(city_state = paste(city, state, sep = ",")) |>  

  filter(!(city_state %in% c("Dallas,TX", "Phoenix,AZ", "Kansas City,MO", "Tulsa,AL"))) |> 

  mutate(
    solved = case_when(
      disposition == "Closed without arrest" ~ 0,
      disposition == "Open/No arrest" ~ 0, 
      disposition == "Closed by arrest" ~ 1,
      TRUE ~ NA_real_  
    )
  ) |> 

  filter(victim_race %in% c("White", "Black")) |>  

  mutate(
    victim_age = as.numeric(victim_age)  
  )
```

```{r}
view(homicide_df)
```

Calculating the estimate and confidence interval of the adjusted odds ratio for solving homicides comparing male victims to female victims keeping all other variables fixed.
```{r}

baltimore_df <- homicide_df |>
  filter(city_state == "Baltimore,MD")

baltimore_reg <- glm(
  solved ~ victim_age + victim_sex + victim_race, 
  data = baltimore_df, 
  family = binomial()  
)

baltimore_OR <- broom::tidy(baltimore_reg) |>
  mutate(
    OR = exp(estimate), 
    CI_upper = exp(estimate + 1.96 * std.error),  # Upper bound of CI
    CI_lower = exp(estimate - 1.96 * std.error)   # Lower bound of CI
  ) |>
  filter(term == "victim_sexMale") |>
  select(OR, CI_lower, CI_upper)  

baltimore_OR
```

Calculating ORs for each city listed 
```{r}
allcity_ORresults <- homicide_df |>
  nest(data = -city_state) |>
  mutate(
    model = map(data, ~ glm(solved ~ victim_age + victim_sex + victim_race, data = .x, family = binomial())), 
    tidy_model = map(model, broom::tidy)
  ) |>
  select(-model, -data) |>
  unnest(cols = tidy_model) |>
  mutate(
    OR = exp(estimate), 
    CI_upper = exp(estimate + 1.96 * std.error),  
    CI_lower = exp(estimate - 1.96 * std.error)   
  ) |>
  filter(term == "victim_sexMale") |>
  select(city_state, OR, CI_upper, CI_lower)

allcity_ORresults |>
  knitr::kable(digits = 4)
```

Creating a plot to display OR data
```{r}
ggplot(allcity_ORresults, aes(x = reorder(city_state, OR), y = OR, ymin = CI_lower, ymax = CI_upper)) +
  geom_pointrange() +
  coord_flip() + 
  labs(
    title = "Estimated Odds Ratios for Solving Homicides: Male vs Female Victims",
    x = "City, State",
    y = "Odds Ratio (OR)",
    caption = "Whiskers represent 95% confidence intervals"
  ) +
  theme_minimal() +
  theme(
    axis.text.y = element_text(size = 8),  
    axis.title = element_text(size = 10)
  )
```



